name: foodo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  flutter:
    sdk: flutter
  geocoding: ^2.0.1
  geolocator: ^8.0.1
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  lottie: ^1.2.1
  lottie_flutter: ^0.2.0
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/FooD.gif
    - assets/images/FooD.png
    - assets/images/cook.png
    - assets/images/offer.png
    - assets/images/delivery.png
    - assets/images/poster.png
    - assets/images/post.png
    - assets/images/bg.png
